name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: env-${{ hashFiles('yarn.lock') }}

    - name: "Install deps"
      run: yarn install

    - name: "Test"
      run: yarn test
